% patchdctfilter applys dct filter for each columned image patches
% 
% Y = patchdctfilter(X,dctfilter)
%
%
%Output parameter:
% Y: filtering results
%
%Input parameters:
% X: columned image patches generated by im2col matlab function
% dctfilter: coefficient map of dctfilter, size(dctfilter,1) * size(dctfilter,2) should equal size(X,1)
%
%
%Example:
% img = double(imread('img.jpg'));
% X = im2col(img,[6 6]);
% dctfilter = ones(6,6);
% dctfilter(1,1)=0;
% dctfilter(1,2)=0;
% dctfilter(2,1)=0;
% Y = patchdctfilter(X,dctfilter)
%
%Version: 20120629

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Miscellaneous tools for image processing                 %
%                                                          %
% Copyright (C) 2012 Masayuki Tanaka. All rights reserved. %
%                    mtanaka@ctrl.titech.ac.jp             %
%                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function Y = patchdctfilter(X,dctfilter)

s = size(dctfilter);
X = reshape(X,[s(1),s(2),size(X,2)]);
Y = eachchannel(@(x)(patchfilter(x,dctfilter)),X);

function y = patchfilter(x,dctfilter)
y = idct2( dctfilter .* dct2(x));
